version: "3.9"
services:
  newbackend:
    container_name: newbackend
    build: ./pm2
    ports:
      - 3002:3002
    restart: always
  nginx-host:
    restart: always
    image: nginx
    ports:
      - 8091:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./web:/usr/share/nginx/html
      - ./nginx/logs:/var/log/nginx
    container_name: nginx-host
